apiVersion: v1
kind: Service
metadata:
  name: products
spec:
  selector:
    app: products
  ports:
    - port: 9091
      targetPort: 8080-tcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products
spec:
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
      annotations:
        revision: "df49fee14a81fd7c7c604ef647f83c3e21b6ce3f"
        buildDate: "20210320182319"
    spec:
      containers:
        - name: products
          image: host.k3d.internal:5000/products:latest
          ports:
            - containerPort: 8080
              name: 8080-tcp
